version: '3'
services:
  test-zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: test-zk
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    networks:
      - test-kafka-net

  test-kafka:
    image: confluentinc/cp-kafka
    container_name: test-kf
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://test-kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=test-zookeeper:2181
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_DELETE_TOPIC_ENABLE=true
    depends_on:
      - test-zookeeper
    networks:
      - test-kafka-net

networks:
  test-kafka-net:
    external: true