version: '3'
services:
  test-zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: test-zk
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    networks:
      - test-kafka-net

  test-kafka1:
    image: confluentinc/cp-kafka
    container_name: test-kf1
    ports:
      - "9092:9092"
    environment:
      #ID 값은 숫자만 가능
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://test-kafka1:9092
      - KAFKA_ZOOKEEPER_CONNECT=test-zookeeper:2181
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_DELETE_TOPIC_ENABLE=true
      # KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      # KAFKA_MIN_INSYNC_REPLICAS=1
    depends_on:
      - test-zookeeper
    networks:
      - test-kafka-net
  
  test-kafka2:
    image: confluentinc/cp-kafka
    container_name: test-kf2
    ports:
      - "9093:9093"
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://test-kafka2:9093
      - KAFKA_ZOOKEEPER_CONNECT=test-zookeeper:2181
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_DELETE_TOPIC_ENABLE=true
      # KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      # KAFKA_MIN_INSYNC_REPLICAS=1
    depends_on:
      - test-zookeeper
    networks:
      - test-kafka-net
  
  test-kafka3:
    image: confluentinc/cp-kafka
    container_name: test-kf3
    ports:
      - "9094:9094"
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://test-kafka3:9094
      - KAFKA_ZOOKEEPER_CONNECT=test-zookeeper:2181
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_DELETE_TOPIC_ENABLE=true
      # KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      # KAFKA_MIN_INSYNC_REPLICAS=1
    depends_on:
      - test-zookeeper
    networks:
      - test-kafka-net

networks:
  test-kafka-net:
    external: true